name: Publish artifacts

on:
    pull_request:
        types: [ labeled, synchronize ]

jobs:
    build-artifacts:
        if: contains(github.event.pull_request.labels.*.name, 'artifact')
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Install node
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - uses: preactjs/compressed-size-action@v2
          with:
            build-script: "build:production"

        # Used to send a comment to the PR with the artifact url
        - name: Save PR number
          run: |
              mkdir -p build/pr_number/
              touch build/pr_number/${{ github.event.number }}

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: limeAppBuild
            path: build/
